[[headers]]
for = "/*"
  [headers.values]
  Content-Security-Policy = "frame-ancestors http://app.storyblok.com/ 20 https://app.storyblok.com/"

[template.environment]
  VITE_STORYBLOK_TOKEN = "Your Storyblok preview token"
